const ACTIONS = {
  SET_INVENTORY: "SET_INVENTORY",
  ADD_ITEM: "ADD_ITEM",
  DELETE_ITEM: "DELETE_ITEM",
  EDIT_ITEM: "EDIT_ITEM",
  UPDATE_ITEM: "UPDATE_ITEM",
  CHECKED_ITEM: "CHECKED_ITEM",
};

export default ACTIONS;
