const ACTIONS = {
  // Item Inventory actions
  SET_INVENTORY: "SET_INVENTORY",
  ADD_ITEM: "ADD_ITEM",
  DELETE_ITEM: "DELETE_ITEM",
  EDIT_ITEM: "EDIT_ITEM",
  TOGGLE_SHOPPING_STATUS: "TOGGLE_SHOPPING_STATUS",
  ADD_ITEM_TO_SHOPPING_LIST: "ADD_ITEM_TO_SHOPPING_LIST",
  DELETE_ITEM_FROM_SHOPPING_LIST: "DELETE_ITEM_FROM_SHOPPING_LIST",
  CHECKED_ITEM: "CHECKED_ITEM",
  // Category actions
  UPDATE_CATEGORY: "UPDATE_CATEGORY",
};

export default ACTIONS;
