const ACTIONS = {
  // Item Inventory actions
  SET_INVENTORY: "SET_INVENTORY",
  ADD_ITEM: "ADD_ITEM",
  DELETE_ITEM: "DELETE_ITEM",
  EDIT_ITEM: "EDIT_ITEM",
  TOGGLE_SHOPPING_STATUS: "TOGGLE_SHOPPING_STATUS",
  CHECKED_ITEM: "CHECKED_ITEM",
  // Category actions
  UPDATE_CATEGORY: "UPDATE_CATEGORY"

};

export default ACTIONS;
